### ISSUE TITLE
importing schema fails

### ISSUE THREAD

**Issue by ghost** [mehcode/python-saml#11]
```python
>>> from saml import schema

# /Users/kadaj/Library/Python/2.7/lib/python/site-packages/saml/schema/utils.pyc matches /Users/kadaj/Library/Python/2.7/lib/python/site-packages/saml/schema/utils.py
import saml.schema.utils # precompiled from /Users/kadaj/Library/Python/2.7/lib/python/site-packages/saml/schema/utils.pyc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kadaj/Library/Python/2.7/lib/python/site-packages/saml/__init__.py", line 12, in <module>
    from .schema import VERSION as SAML_VERSION
  File "/Users/kadaj/Library/Python/2.7/lib/python/site-packages/saml/schema/__init__.py", line 24, in <module>
    from .saml import *  # noqa
  File "/Users/kadaj/Library/Python/2.7/lib/python/site-packages/saml/schema/saml.py", line 4, in <module>
    from . import types, base, VERSION
  File "/Users/kadaj/Library/Python/2.7/lib/python/site-packages/saml/schema/base.py", line 281, in <module>
    class Base(six.with_metaclass(Declarative)):
  File "/Users/kadaj/Library/Python/2.7/lib/python/site-packages/saml/schema/base.py", line 114, in __new__
    _element_registry[obj.name] = obj
  File "/Users/kadaj/Library/Python/2.7/lib/python/site-packages/saml/schema/utils.py", line 24, in __get__
    return self.getter(cls)
  File "/Users/kadaj/Library/Python/2.7/lib/python/site-packages/saml/schema/base.py", line 299, in name
    return '{%s}%s' % (cls.meta.namespace[1], cls.meta.name)
TypeError: Error when calling the metaclass bases
    'NoneType' object has no attribute '__getitem__'
```

**Comment by ghost** [comment]
Sorry, duplicate of #6.
```bash
pip install --user six --upgrade
```
fixed.
