### ISSUE TITLE
Error on import

### ISSUE THREAD

**Issue by countergram** [mehcode/python-saml#6]
```
>>> import saml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/saml/__init__.py", line 12, in <module>
    from .schema import VERSION as SAML_VERSION
  File "/usr/local/lib/python2.7/site-packages/saml/schema/__init__.py", line 24, in <module>
    from .saml import *  # noqa
  File "/usr/local/lib/python2.7/site-packages/saml/schema/saml.py", line 4, in <module>
    from . import types, base, VERSION
  File "/usr/local/lib/python2.7/site-packages/saml/schema/base.py", line 281, in <module>
    class Base(six.with_metaclass(Declarative)):
  File "/usr/local/lib/python2.7/site-packages/saml/schema/base.py", line 114, in __new__
    _element_registry[obj.name] = obj
  File "/usr/local/lib/python2.7/site-packages/saml/schema/utils.py", line 24, in __get__
    return self.getter(cls)
  File "/usr/local/lib/python2.7/site-packages/saml/schema/base.py", line 299, in name
    return '{%s}%s' % (cls.meta.namespace[1], cls.meta.name)
TypeError: Error when calling the metaclass bases
    'NoneType' object has no attribute '__getitem__'
```

Appears to happen because it's trying to add the `Base` class to the registry but `Base` does not have `namespace`

**Comment by countergram** [comment]
Updating `six` (was 1.6.1, now 1.9) seems to have fixed this.
