### ISSUE TITLE
Installation fails for pip

### ISSUE THREAD

**Issue by ghost** [mehcode/python-saml#9]
I am getting the following error when I try to install using `pip install .`. I tried `pip install saml` which also produces same error. The `xmlsec` package fails. Before running `pip` I have installed dependencies using brew.
``` bash
brew install libxml2 libxmlsec1
```
``` bash
pip install .
Processing /Users/kadaj/dev/python/python-saml
Requirement already satisfied: python-dateutil in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from saml==0.9.0)
Requirement already satisfied: lxml in /Users/kadaj/Library/Python/2.7/lib/python/site-packages (from saml==0.9.0)
Collecting xmlsec (from saml==0.9.0)
  Using cached xmlsec-0.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    no previously-included directories found matching 'doc/.build'
    
    Installed /private/var/folders/9m/_fh0czw947g8q7pdhxbfbjdh0000gn/T/easy_install-GdJMQ3/pkgconfig-1.2.2/.eggs/nose-1.3.7-py2.7.egg
    zip_safe flag not set; analyzing archive contents...
    
    Installed /private/var/folders/9m/_fh0czw947g8q7pdhxbfbjdh0000gn/T/pip-build-YXpuD7/xmlsec/.eggs/pkgconfig-1.2.2-py2.7.egg
    Searching for setuptools-cython
    Reading https://pypi.python.org/simple/setuptools_cython/
    Best match: setuptools-cython 0.2.1
    Downloading https://pypi.python.org/packages/34/de/d21aeeaccc38f3753d06a30e2eabcf56d39eb345cdc6a8e4610d69fef13f/setuptools_cython-0.2.1.tar.gz#md5=c29fc5bf2894e69cbd98e3800cef4707
    Processing setuptools_cython-0.2.1.tar.gz
    Writing /var/folders/9m/_fh0czw947g8q7pdhxbfbjdh0000gn/T/easy_install-stHTy9/setuptools_cython-0.2.1/setup.cfg
    Running setuptools_cython-0.2.1/setup.py -q bdist_egg --dist-dir /var/folders/9m/_fh0czw947g8q7pdhxbfbjdh0000gn/T/easy_install-stHTy9/setuptools_cython-0.2.1/egg-dist-tmp-R6DL8Y
    zip_safe flag not set; analyzing archive contents...
    Copying setuptools_cython-0.2.1-py2.7.egg to /private/var/folders/9m/_fh0czw947g8q7pdhxbfbjdh0000gn/T/pip-build-YXpuD7/xmlsec/.eggs
    
    Installed /private/var/folders/9m/_fh0czw947g8q7pdhxbfbjdh0000gn/T/pip-build-YXpuD7/xmlsec/.eggs/setuptools_cython-0.2.1-py2.7.egg
    running egg_info
    creating pip-egg-info/xmlsec.egg-info
    writing requirements to pip-egg-info/xmlsec.egg-info/requires.txt
    writing pip-egg-info/xmlsec.egg-info/PKG-INFO
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/9m/_fh0czw947g8q7pdhxbfbjdh0000gn/T/pip-build-YXpuD7/xmlsec/setup.py", line 123, in <module>
        make_extension('xmlsec.template'),
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/egg_info.py", line 173, in run
        writer(self, ep.name, os.path.join(self.egg_info, ep.name))
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/egg_info.py", line 434, in write_toplevel_names
        for k in cmd.distribution.iter_distribution_names()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 665, in iter_distribution_names
        name = ext.name
      File "/private/var/folders/9m/_fh0czw947g8q7pdhxbfbjdh0000gn/T/pip-build-YXpuD7/xmlsec/setup.py", line 27, in __getattr__
        **self.__arguments["kwargs"])
      File "/private/var/folders/9m/_fh0czw947g8q7pdhxbfbjdh0000gn/T/pip-build-YXpuD7/xmlsec/setup.py", line 54, in make_extension
        config.update(parse(lib))
      File "build/bdist.macosx-10.12-intel/egg/pkgconfig/pkgconfig.py", line 207, in parse
      File "build/bdist.macosx-10.12-intel/egg/pkgconfig/pkgconfig.py", line 181, in parse_package
      File "build/bdist.macosx-10.12-intel/egg/pkgconfig/pkgconfig.py", line 61, in _wrapper
    EnvironmentError: pkg-config is not installed
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/9m/_fh0czw947g8q7pdhxbfbjdh0000gn/T/pip-build-YXpuD7/xmlsec/
```

**Comment by digitalresistor** [comment]
brew install pkgconfig

You are missing a dependency.

**Comment by ghost** [comment]
Thanks.
